language: java
jdk:
  - oraclejdk8

install: ant

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - p.degiano@fi.uba.ar
      - manuel.radrizzani@outlook.com
    on_failure: always
